FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

# Cài đặt tất cả dependencies
RUN npm install

# Mở port 5173 (Port mặc định của Vite)
EXPOSE 5173

# Chạy vite server với host 0.0.0.0
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
